// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://pelykusygwjztlqwljko.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InBlbHlrdXN5Z3dqenRscXdsamtvIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTU1MjkxNzQsImV4cCI6MjA3MTEwNTE3NH0.jmRbGmW9K4jikkMWhepts9A4npDJDCZG9ku8UK-25cE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});